package reminder.application

import reminder.domain.*
import java.util.*

class ReminderSaver(
    private val repository: ReminderRepository,
    private val identifierGenerator: ReminderIdentifierGenerator,
) {

    /***
     * Creates a Reminder with the identifier generated by the identifierGenerator instance and
     * saves it to the given repository.
     * @see Reminder
     * @see ReminderIdentifierGenerator
     * @return The saved reminder instance
     */
    fun save(title: String, description: Optional<String>): Reminder {
        val reminder = Reminder(
            id = identifierGenerator.generate(),
            title = Title(title),
            description = description.map { Description(it) })
        repository.save(reminder)
        return reminder
    }

}