#!/usr/bin/env bash
# KTLINT FORMAT

echo "***********************************************"
echo "            Formatting with ktlint             "
echo "***********************************************"
changed_kotlin_files=$(git diff --cached --name-only --diff-filter=ACMR | grep ".*kt$" )
echo $changed_kotlin_files

if [ -z "$changed_kotlin_files" ]; then
  echo "No kotlin files to format"
  exit 0
fi

ktlint $changed_kotlin_files

if [ $? -ne 0 ]; then
  ktlint -F $changed_kotlin_files
  echo "***********************************************"
  echo "                 Ktlint failed                 "
  echo " Please fix the above issues before committing "
  echo "***********************************************"
  exit 1
fi

# DETECT
echo "***********************************************"
echo "          Running detekt on changed files      "
echo "***********************************************"
OUTPUT="/tmp/detekt-$(date +%s)"
mvn detekt:check > $OUTPUT
EXIT_CODE=$?
if [ $EXIT_CODE -ne 0 ]; then
  cat $OUTPUT
  rm $OUTPUT
  echo "***********************************************"
  echo "                 Detekt failed                 "
  echo " Please fix the above issues before committing "
  echo "***********************************************"
  exit $EXIT_CODE
fi
rm $OUTPUT


# KTLINT CHECK
changed_kotlin_files=$(git diff --cached --name-only --diff-filter=ACMR | grep ".*kt$" )
echo $changed_kotlin_files
ktlint $changed_kotlin_files